name: Dev Checks

on: 
  push:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-verion: [22.x]
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Configure Node
        uses: actions/setup-node@v3
        with:
          node-verions: ${{ matrix.node-verion }}

      - name: Install Dependencies
        run: npm install

      # - name: Run Tests
      #   run: npm test

      - name: Build Project
        run: npm run build
 
